"""
Global settings module for the game.
Contains variables shared between different modules.
"""

SOUND_ENABLED = True

SCREEN_WIDTH = 850
SCREEN_HEIGHT = 550
GAME_TITLE = 'PyDragon v0.5'

FPS = 60
ORIGINAL_FPS = 24
MOVE_SPEED = 8.0
SPEED_ADJUSTMENT = ORIGINAL_FPS / FPS
VSYNC = True
HARDWARE_ACCELERATION = True
AUDIO_BUFFER_SIZE = 512

ENABLE_SMOOTH_SCALING = True
SHOW_FPS = False
SPRITE_CACHING = True

BACKGROUND_LOADING = False
LOW_QUALITY_MODE = False
